In [294]:
import numpy as np

In [295]:
np.__version__

'1.10.4'

In [296]:
cd C:\Users\embarcados\Desktop\ml-data\data

C:\Users\embarcados\Desktop\ml-data\data


In [297]:
import csv

In [298]:
iris_file = open("C:\Users\embarcados\Desktop\ml-data\data\iris.data", "rb")
csv_handler = csv.reader(iris_file)

In [299]:
header = csv_handler.next()

In [300]:
header

['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

In [301]:
data = []

In [302]:
for row in csv_handler:
    data.append(row)

In [303]:
data

[['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
 ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
 ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
 ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
 ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
 ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
 ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
 ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
 ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
 ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
 ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
 ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
 ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
 ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
 ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
 ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
 ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
 ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
 ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
 ['5.1', '3.8', '1.5', '0.3', 'Iris-setosa'],
 ['5.4', '3.4', '1.7', '0.2', 'Iris-setosa'],
 ['5.1', '3.7', '1.5', '0.4', 'Iri

In [304]:
data = np.array(data)

In [305]:
data.shape

(150L, 5L)

In [306]:
data.ndim

2

In [307]:
data[0, :]

array(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], 
      dtype='|S15')

In [308]:
data[1, :]

array(['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], 
      dtype='|S15')

In [309]:
data[-1, :]

array(['5.9', '3.0', '5.1', '1.8', 'Iris-virginica'], 
      dtype='|S15')

In [310]:
data[:, 0]

array(['5.1', '4.9', '4.7', '4.6', '5.0', '5.4', '4.6', '5.0', '4.4',
       '4.9', '5.4', '4.8', '4.8', '4.3', '5.8', '5.7', '5.4', '5.1',
       '5.7', '5.1', '5.4', '5.1', '4.6', '5.1', '4.8', '5.0', '5.0',
       '5.2', '5.2', '4.7', '4.8', '5.4', '5.2', '5.5', '4.9', '5.0',
       '5.5', '4.9', '4.4', '5.1', '5.0', '4.5', '4.4', '5.0', '5.1',
       '4.8', '5.1', '4.6', '5.3', '5.0', '7.0', '6.4', '6.9', '5.5',
       '6.5', '5.7', '6.3', '4.9', '6.6', '5.2', '5.0', '5.9', '6.0',
       '6.1', '5.6', '6.7', '5.6', '5.8', '6.2', '5.6', '5.9', '6.1',
       '6.3', '6.1', '6.4', '6.6', '6.8', '6.7', '6.0', '5.7', '5.5',
       '5.5', '5.8', '6.0', '5.4', '6.0', '6.7', '6.3', '5.6', '5.5',
       '5.5', '6.1', '5.8', '5.0', '5.6', '5.7', '5.7', '6.2', '5.1',
       '5.7', '6.3', '5.8', '7.1', '6.3', '6.5', '7.6', '4.9', '7.3',
       '6.7', '7.2', '6.5', '6.4', '6.8', '5.7', '5.8', '6.4', '6.5',
       '7.7', '7.7', '6.0', '6.9', '5.6', '7.7', '6.3', '6.7', '7.2',
       '6.2', '6.1',

In [311]:
data[0:5, :]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']], 
      dtype='|S15')

In [312]:
data[1:6, :]

array([['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa']], 
      dtype='|S15')

In [313]:
data[0:5, 0:2]

array([['5.1', '3.5'],
       ['4.9', '3.0'],
       ['4.7', '3.2'],
       ['4.6', '3.1'],
       ['5.0', '3.6']], 
      dtype='|S15')

In [314]:
target = data[:, -1]
target

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [315]:
data = data[:, 0:-1]

In [316]:
data

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [317]:
data = data.astype(np.float)

In [318]:
data

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [319]:
header

['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

In [320]:
mask = data[:, 3] < 0.6
data[mask, :]
target[mask]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], 
      dtype='|S15')

In [321]:
mask = (data[:, 3] > 0.6) & (data[:, 3] <= 1.7) & (data[:,2] <= 4.9)

In [322]:
target[mask]

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicol

In [323]:
data[:,0].sum()

876.5

In [324]:
data[:,0].min()

4.2999999999999998

In [325]:
data[:,0].mean()

5.8433333333333337

In [326]:
data[:,0].std()

0.82530129178514089

In [327]:
target[0:5] # apenas nomes

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], 
      dtype='|S15')

In [328]:
np.unique(target)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], 
      dtype='|S15')

In [329]:
target_names = np.unique(target)

In [330]:
for idx, row in enumerate(target):
    print(idx,row)

(0, 'Iris-setosa')
(1, 'Iris-setosa')
(2, 'Iris-setosa')
(3, 'Iris-setosa')
(4, 'Iris-setosa')
(5, 'Iris-setosa')
(6, 'Iris-setosa')
(7, 'Iris-setosa')
(8, 'Iris-setosa')
(9, 'Iris-setosa')
(10, 'Iris-setosa')
(11, 'Iris-setosa')
(12, 'Iris-setosa')
(13, 'Iris-setosa')
(14, 'Iris-setosa')
(15, 'Iris-setosa')
(16, 'Iris-setosa')
(17, 'Iris-setosa')
(18, 'Iris-setosa')
(19, 'Iris-setosa')
(20, 'Iris-setosa')
(21, 'Iris-setosa')
(22, 'Iris-setosa')
(23, 'Iris-setosa')
(24, 'Iris-setosa')
(25, 'Iris-setosa')
(26, 'Iris-setosa')
(27, 'Iris-setosa')
(28, 'Iris-setosa')
(29, 'Iris-setosa')
(30, 'Iris-setosa')
(31, 'Iris-setosa')
(32, 'Iris-setosa')
(33, 'Iris-setosa')
(34, 'Iris-setosa')
(35, 'Iris-setosa')
(36, 'Iris-setosa')
(37, 'Iris-setosa')
(38, 'Iris-setosa')
(39, 'Iris-setosa')
(40, 'Iris-setosa')
(41, 'Iris-setosa')
(42, 'Iris-setosa')
(43, 'Iris-setosa')
(44, 'Iris-setosa')
(45, 'Iris-setosa')
(46, 'Iris-setosa')
(47, 'Iris-setosa')
(48, 'Iris-setosa')
(49, 'Iris-setosa')
(50, 'Iris

In [331]:
target_raw = target.copy()

In [332]:
for idx,row in enumerate(target):
    if row == "Iris-setosa": target[idx] = 0
    if row == "Iris-versicolor": target[idx] = 1
    if row == "Iris-virginica": target[idx] = 2

In [333]:
target = target.astype(np.int)
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [334]:
data[0:5,]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [335]:
150*0.8

120.0

In [336]:
idx = np.random.choice(150, size=120)

In [337]:
dims = [2, 3]
data_dim = data[:, dims]

train_data = data_dim[idx, :]
test_data = data_dim[~idx, :]

In [338]:
train_target = target[idx]
test_target = target[~idx]

In [339]:
import sklearn

In [340]:
from sklearn.tree import DecisionTreeClassifier

In [341]:
clf = DecisionTreeClassifier()

In [342]:
clf = clf.fit(train_data, train_target)

In [343]:
pred = clf.predict(test_data)

In [344]:
pred

array([1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1,
       2, 1, 1, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 1, 0, 0, 1, 0, 0, 1, 2, 2, 2,
       1, 1, 1, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 2, 2, 1, 2, 0, 2, 2, 0, 2, 2,
       1, 0, 1, 0, 2, 1, 0, 1, 2, 0, 2, 1, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 2,
       0, 0, 0, 0, 2])

In [345]:
test_target - pred

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1])

In [346]:
import matplotlib.pyplot as plt

# Plot the decision boundary
def plot_decision_boundary(X, Y, clf):
    # Some variables
    n_classes = 3
    plot_colors = "bry"
    plot_step = 0.02
    # Set min and max for two dimensions
    x_min, x_max = X[:,0].min() - 1, X[:,0].max() + 1
    y_min, y_max = X[:,1].min() - 1, X[:,1].max() + 1
    # Create matrix of steps from min to max
    xx, yy = np.meshgrid(np.arange(x_min, x_max, plot_step), np.arange(y_min, y_max, plot_step))
    # Predict every point from the matrix
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    # what?
    Z = Z.reshape(xx.shape)
    # Plot contour
    cs = plt.contourf(xx, yy, Z, cmap=plt.cm.Paired)
    # Set labels
    plt.xlabel(header[dims[0]])
    plt.ylabel(header[dims[1]])
    plt.axis("tight")
    # Plot train points, colored by class
    for i, color in zip(range(n_classes), plot_colors):
        idx = np.where(Y == i)
        plt.scatter(X[idx,0], X[idx,1], c=color, label=target_names[i], cmap=plt.cm.Paired)

In [347]:
plot_decision_boundary(train_data, train_target, clf)
# plt.show()

In [348]:
from sklearn.cross_validation import cross_val_score

In [349]:
cv = cross_val_score(clf, data_dim, target, cv=10)

In [350]:
cv.mean()

0.94666666666666666

In [351]:
cv.std()

0.058118652580542302

In [381]:
from sklearn.neighbors import KNeighborsClassifier

In [382]:
clf = KNeighborsClassifier(n_neighbors = 2)

In [383]:
clf = clf.fit(train_data, train_target)

In [384]:
pred = clf.predict(test_data)

In [385]:
pred - test_target

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        1])

In [386]:
plot_decision_boundary(train_data, train_target, clf)
# plt.show()

In [387]:
cv = cross_val_score(clf, data_dim, target, cv=10)

In [389]:
cv.mean()

0.95999999999999996

In [ ]:
classifier = [
    KNeighborsClassifier(n_neighbors = 1),
    KNeighborsClassifier(n_neighbors = 3),
    KNeighborsClassifier(n_neighbors = 5),
    DecisionTreeClassifier()
]

for idx, clf in enumerate(classifier):
    clf = clf.fit(train_data, train_target)
    pred = clf.predict(test_data)
    err = np.sum((pred - test_target) != 0)
    print("Number of misclassifications = %d" % (err))
    plt.subplot(2, 2, idx + 1)
    plot_decision_boundary(train_data, train_target, clf)

plt.show()